#!/usr/bin/env zsh

# function to shame the user for forgetting they weren't in vim
not-vim () {
    # pull in config for which "sayer" program
    local say_program
    zstyle -s :plugins:not-vim say say_program
    say_program="${say_program:-cowsay}"

    # make sure cowsay is installed if there isn't a custom sayer
    if test "$say_program" = "cowsay"; then
      if (( ! $+commands[cowsay] )); then
          echo "cowsay not installed"
          return 1
      fi
    fi

    # do the thing (split $say_program on space to allow for args)
    echo "You're not in vim idiot, you're in your shell!" | ${(@s/ /)say_program}
}

